
### signup
POST http://localhost:5000/web-hct/us-central1/app/api/auth/signup
content-Type: application/json

{
    "username": "javier896",
    "password": "Pepito01*",
    "email": "javier.ss896@gmail.com",
    "name": "Pepito",
    "identification_card": "0000-0000-00000",
    "phone": "504 99999999",
    "city": "San Pedro Sula",
    "address": "No sé",
    "company": "Microsoft"
}

### signin

POST http://localhost:5000/web-hct/us-central1/app/api/auth/signin
content-Type: application/json

{
    "username": "pepito001",
    "password": "Pepito01*",
    "email": ""
}


### change password

POST http://localhost:5000/web-hct/us-central1/app/api/auth/change-password
content-Type: application/json

{
    "username": "javier896",
    "password": "Password@2",
    "email": "javier.ss896@gmail.com"
}