
### Add Category whit SubCategories
// Si la categoría existe, las subcategías se agregaran a la categoría.
POST http://localhost:5000/web-hct/us-central1/app/api/categories/new
content-Type: application/json

{
    "name": "electrónica",
    "active": true,
    "subCategories": [
        {
            "name": "electrónica 1",
            "description": "This is new subCategory",
            "active": true
        }
    ]
}

### Add SubCategories to categoryId (send by url param :categoryId)
POST http://localhost:5000/web-hct/us-central1/app/api/categories/2/sub-categories/news
content-Type: application/json

{
    "subCategories": [
        {
            "name": "electrónica 2",
            "description": "This is new subCategory",
            "active": true
        }
    ]
}

### Get All Categories with SubCategories

GET http://localhost:5000/web-hct/us-central1/app/api/categories HTTP/1.1