
### Get By UserId
GET http://localhost:5000/web-hct/us-central1/app/api/wish-list/mREwoj4vgUHqq5Lh


### Add product to whish list

POST http://localhost:5000/web-hct/us-central1/app/api/wish-list/new
content-Type: application/json

{
    "userId": "mREwoj4vgUHqq5Lh",
    "productUid": "1f62ce4b-3483-11ed-bb28-00be431e17e1"
}


### Add products to whish list

POST http://localhost:5000/web-hct/us-central1/app/api/wish-list/news
content-Type: application/json

{
    "userId": "MzGDRZdknKC6saI6",
    "productIds": [3, 4, 2]
}


### Delete product by WhisListId
DELETE http://localhost:5000/web-hct/us-central1/app/api/wish-list/2